import type { Metadata } from "next";
import { Anton } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container } from "react-bootstrap";
import { Suspense } from "react";
const inter = Anton({ subsets: ["latin"],weight:["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Swir</title>
        <link rel="icon" href="/favicon.ico"></link>
      </head>
      <body className={inter.className}>
        <Container className="py-4">
          <Suspense>
        {children}
          </Suspense>
        </Container>
      </body>
    </html>
  );
}
